// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEfUgt467F_NBWlS74PwPMGvORBRyCkCM',
    appId: '1:492410104110:web:2e91b012c6ec4f15dff2bf',
    messagingSenderId: '492410104110',
    projectId: 'cricket-borigivalasa',
    authDomain: 'cricket-borigivalasa.firebaseapp.com',
    storageBucket: 'cricket-borigivalasa.firebasestorage.app',
    measurementId: 'G-T48F8Q243X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5YF7El-_FJAQuK8N-8q6Ecdb9m3Mi2ss',
    appId: '1:492410104110:android:21654ad6fbe22401dff2bf',
    messagingSenderId: '492410104110',
    projectId: 'cricket-borigivalasa',
    storageBucket: 'cricket-borigivalasa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8cA6qHIeR8Q7zr92Ot9GDvZj3ff5LcgA',
    appId: '1:492410104110:ios:28196682b1252adbdff2bf',
    messagingSenderId: '492410104110',
    projectId: 'cricket-borigivalasa',
    storageBucket: 'cricket-borigivalasa.firebasestorage.app',
    iosBundleId: 'com.yourdomain.cricketScoringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8cA6qHIeR8Q7zr92Ot9GDvZj3ff5LcgA',
    appId: '1:492410104110:ios:28196682b1252adbdff2bf',
    messagingSenderId: '492410104110',
    projectId: 'cricket-borigivalasa',
    storageBucket: 'cricket-borigivalasa.firebasestorage.app',
    iosBundleId: 'com.yourdomain.cricketScoringApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEfUgt467F_NBWlS74PwPMGvORBRyCkCM',
    appId: '1:492410104110:web:b4e3bccb5584707adff2bf',
    messagingSenderId: '492410104110',
    projectId: 'cricket-borigivalasa',
    authDomain: 'cricket-borigivalasa.firebaseapp.com',
    storageBucket: 'cricket-borigivalasa.firebasestorage.app',
    measurementId: 'G-DP9TXZ27V7',
  );
}
